version: "3.8"
services:
  pg:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 80:80
      - 443:443
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
  quarkus:
    build: .
    volumes:
      - ./learn:/usr/src/app
    ports:
      - 8080:8080
    links:
      - postgres
